theme: jekyll-theme-hacker
url: "https://titusstudios.net/"
title: Titus Studios
description: I do software development and web technologies.
logo: /assets/images/newlogo2020.png
gems:             [jekyll-seo-tag, jekyll-sitemap]
defaults:
  -
    scope:
      path:            "assets/*"
      path:            "data/*"
    values:
      sitemap:         false
