theme: jekyll-theme-hacker
google_analytics: UA-142625828-2

url: "https://titusstudios.net/" # the hostname & protocol for your site
title: Titus Studios
description: Titus Studios Official Website. Endeavour on the adventures of Titus and the company Titus Studios Media, a New Zealand Media Production business dedicated to high quality web media since 2013.

gems: 
      - jekyll-sitemap
      
defaults:
  -
    scope:
      path:            "assets/**/*"
      path:            "data/**/"
    values:
      sitemap:         false

      
