url: "https://aerofur.nz/"
title: www.aerofur.nz
description: dog on the internet.
gems: [jekyll-sitemap]
defaults:
  -
    scope:
      path: "modules/*"
      path: "data/*"
    values:
      sitemap: false