theme: jekyll-theme-hacker
google_analytics: UA-142625828-1

baseurl: "https://www.titusstudios.net/" # the base hostname & protocol for your site
url: "https://www.titusstudios.net/" # the hostname & protocol for your site
title: Titus Studios
description: Titus Studios Official Website | Endeavour on the adventures of Titus and the company Titus Studios Media, a New Zealand Media Production business dedicated to high quality web media.

gems: 
      - jekyll-sitemap
      - jekyll-seo-tag
      
defaults:
  -
    scope:
      path:            "assets/**/*"
      path:            "data/**/"
    values:
      sitemap:         false
